# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 3.4.0b5
_src_path: gh:epics-containers/ioc-template
description: Generic IOC for simulation motors
git_platform: github.com
github_org: epics-containers
name: ioc-motorsim
repo_uri: git@github.com:epics-containers/ioc-motorsim.git
rtems: true
